name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: redwoodjs/project-ci-action@main
        with:
          run-lint: 'no'

